<?php

return [
    'module_order' => [
        'Administrare acces',
        'Utilizatori',
        'Locații',
        'Nomenclator',
        'Furnizori',
        'Inventar',
        'Echipamente',
        'Proiecte',
        'Transferuri',
        'Sarcini șoferi',
        'Recepții',
        'Comenzi negociate',
        'Consum',
        'Custodie',
        'Rapoarte',
        'Alerte',
        'Teren',
        'Sistem',
    ],

    'scope_labels' => [
        'global' => 'Toată aplicația',
        'assigned_locations' => 'Locațiile administrate',
        'selected_location' => 'Locația selectată',
        'destination_location' => 'Locația destinație',
        'assigned_records' => 'Înregistrările alocate',
        'personal' => 'Datele și bunurile proprii',
        'visible_records' => 'Înregistrările deja vizibile',
        'lookup' => 'Consultare punctuală',
        'protected_identity' => 'Contul protejat',
    ],

    'reserved_permissions' => [
        'access.view',
        'roles.manage',
        'permissions.assign-direct',
        'users.view',
        'users.manage',
        'users.assign-roles',
        'users.impersonate',
        'locations.assign-responsibles',
        'alerts.manage',
        'access-database-tools',
    ],

    'direct_exception_permissions' => [
        'locations.view',
        'catalog.view',
        'catalog.manage',
        'suppliers.view',
        'suppliers.manage',
        'inventory.view',
        'inventory.view-commercial',
        'inventory.manage',
        'tracked-assets.browse',
        'tracked-assets.view',
        'tracked-assets.manage',
        'projects.view',
        'projects.manage',
        'transfers.view',
        'transfers.create',
        'transfers.update',
        'transfers.approve',
        'transfers.receive',
        'transfers.cancel',
        'transfers.archive',
        'tasks.view',
        'tasks.create',
        'tasks.update',
        'tasks.assign',
        'tasks.respond',
        'tasks.comment',
        'tasks.transition',
        'reception-intakes.view',
        'reception-intakes.create',
        'reception-intakes.cancel',
        'receptions.view',
        'receptions.create',
        'reception-documents.upload',
        'reception-details.edit-all',
        'reception-details.edit-expiration',
        'accounting.edit-operations',
        'negotiated-orders.view',
        'negotiated-orders.manage',
        'consumption-reports.view',
        'consumption-reports.create',
        'consumption-reports.correct',
        'custody.view',
        'custody.initiate',
        'custody.manage',
        'reports.view',
        'alerts.view',
        'qr.scan',
    ],

    'roles' => [
        'super-admin' => [
            'description' => 'Cont protejat cu acces operațional complet și capabilități de sistem rezervate.',
            'workspace' => 'Operațional',
            'system' => true,
            'privileged' => true,
            'requires_locations' => false,
        ],
        'admin' => [
            'description' => 'Administrează utilizatorii și majoritatea configurărilor și operațiunilor.',
            'workspace' => 'Operațional',
            'system' => true,
            'privileged' => true,
            'requires_locations' => false,
        ],
        'dispecer' => [
            'description' => 'Coordonează global locațiile, stocurile, transferurile și sarcinile.',
            'workspace' => 'Operațional',
            'system' => true,
            'privileged' => false,
            'requires_locations' => false,
        ],
        'manager' => [
            'description' => 'Consultă global activitatea și administrează planificarea proiectelor.',
            'workspace' => 'Management',
            'system' => true,
            'privileged' => false,
            'requires_locations' => false,
        ],
        'gestionar-baza' => [
            'description' => 'Lucrează operațional în bazele și locațiile pentru care este responsabil.',
            'workspace' => 'Responsabil locație',
            'system' => true,
            'privileged' => false,
            'requires_locations' => true,
        ],
        'sef-santier' => [
            'description' => 'Lucrează operațional în șantierele și locațiile pentru care este responsabil.',
            'workspace' => 'Responsabil locație',
            'system' => true,
            'privileged' => false,
            'requires_locations' => true,
        ],
        'sofer' => [
            'description' => 'Lucrează cu sarcinile și transferurile care îi sunt alocate.',
            'workspace' => 'Șofer',
            'system' => true,
            'privileged' => false,
            'requires_locations' => false,
        ],
        'muncitor' => [
            'description' => 'Lucrează cu bunurile proprii, custodia și documentele trimise.',
            'workspace' => 'Muncitor',
            'system' => true,
            'privileged' => false,
            'requires_locations' => false,
        ],
        'contabil' => [
            'description' => 'Consultă global informațiile comerciale, recepțiile, consumul și rapoartele.',
            'workspace' => 'Contabilitate',
            'system' => true,
            'privileged' => false,
            'requires_locations' => false,
        ],
        'user' => [
            'description' => 'Cont autentificat fără acces operațional implicit.',
            'workspace' => 'Limitat',
            'system' => true,
            'privileged' => false,
            'requires_locations' => false,
        ],
    ],

    'permissions' => [
        'access.view' => [
            'module' => 'Administrare acces',
            'label' => 'Consultă accesul utilizatorilor',
            'description' => 'Deschide centrul de acces, matricea rolurilor și explicațiile pentru fiecare utilizator.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'roles.manage' => [
            'module' => 'Administrare acces',
            'label' => 'Administrează rolurile și drepturile',
            'description' => 'Creează roluri personalizate și modifică drepturile rolurilor configurabile.',
            'risk' => 'protected',
            'direct_scope' => 'protected_identity',
            'reserved' => true,
            'grants' => ['super-admin' => 'protected_identity'],
        ],
        'permissions.assign-direct' => [
            'module' => 'Administrare acces',
            'label' => 'Atribuie excepții directe',
            'description' => 'Acordă sau retrage excepții justificate pentru un utilizator individual.',
            'risk' => 'protected',
            'direct_scope' => 'protected_identity',
            'reserved' => true,
            'grants' => ['super-admin' => 'protected_identity'],
        ],
        'users.view' => [
            'module' => 'Utilizatori',
            'label' => 'Consultă utilizatorii',
            'description' => 'Vede conturile, rolurile și responsabilitățile disponibile administrării.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'users.manage' => [
            'module' => 'Utilizatori',
            'label' => 'Administrează utilizatorii',
            'description' => 'Creează conturi și modifică identitatea, parola și starea lor.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'users.assign-roles' => [
            'module' => 'Utilizatori',
            'label' => 'Atribuie roluri',
            'description' => 'Atribuie rolurile operaționale permise și verifică efectul lor.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'users.impersonate' => [
            'module' => 'Utilizatori',
            'label' => 'Schimbă temporar utilizatorul',
            'description' => 'Intră controlat și auditat în contul unui utilizator eligibil.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'condition' => 'Sunt excluse conturile administrative și sesiunile neeligibile.',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'locations.view' => [
            'module' => 'Locații',
            'label' => 'Consultă locațiile',
            'description' => 'Vede locațiile și responsabilii aferenți domeniului de acces.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'locations.manage' => [
            'module' => 'Locații',
            'label' => 'Administrează locațiile',
            'description' => 'Creează și modifică datele locațiilor.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global'],
        ],
        'locations.assign-responsibles' => [
            'module' => 'Locații',
            'label' => 'Stabilește responsabilii locației',
            'description' => 'Atribuie persoane eligibile care primesc notificări și pot lucra pentru locație.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global'],
        ],
        'catalog.view' => [
            'module' => 'Nomenclator',
            'label' => 'Consultă nomenclatorul',
            'description' => 'Vede materialele, sculele și echipamentele definite în aplicație.',
            'risk' => 'normal',
            'direct_scope' => 'global',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'global', 'sef-santier' => 'global',
            ],
        ],
        'catalog.manage' => [
            'module' => 'Nomenclator',
            'label' => 'Administrează nomenclatorul',
            'description' => 'Creează și modifică articolele din nomenclator.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'gestionar-baza' => 'global',
            ],
        ],
        'suppliers.view' => [
            'module' => 'Furnizori',
            'label' => 'Consultă furnizorii',
            'description' => 'Vede furnizorii și istoricul lor operațional.',
            'risk' => 'normal',
            'direct_scope' => 'global',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'global', 'sef-santier' => 'global', 'contabil' => 'global',
            ],
        ],
        'suppliers.manage' => [
            'module' => 'Furnizori',
            'label' => 'Administrează furnizorii',
            'description' => 'Creează, modifică, activează și dezactivează furnizorii.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'contabil' => 'global',
            ],
        ],
        'inventory.view' => [
            'module' => 'Inventar',
            'label' => 'Consultă inventarul',
            'description' => 'Vede stocurile și mișcările din domeniul de acces.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'contabil' => 'global',
            ],
        ],
        'inventory.view-commercial' => [
            'module' => 'Inventar',
            'label' => 'Consultă valorile comerciale',
            'description' => 'Vede prețurile, monedele și valorile comerciale din inventar și recepții.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global', 'contabil' => 'global',
            ],
        ],
        'inventory.manage' => [
            'module' => 'Inventar',
            'label' => 'Administrează operațiunile de inventar',
            'description' => 'Folosește acțiunile administrative care pot influența evidența inventarului.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'condition' => 'Regulile de stoc și istoricul mișcărilor rămân obligatorii.',
            'grants' => ['super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global'],
        ],
        'tracked-assets.browse' => [
            'module' => 'Echipamente',
            'label' => 'Consultă lista echipamentelor',
            'description' => 'Parcurge echipamentele globale sau din locațiile administrate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'tracked-assets.view' => [
            'module' => 'Echipamente',
            'label' => 'Deschide fișa unui echipament',
            'description' => 'Consultă o fișă disponibilă prin listă, custodie sau scanare QR.',
            'risk' => 'normal',
            'direct_scope' => 'lookup',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
                'sofer' => 'lookup', 'muncitor' => 'lookup', 'contabil' => 'lookup',
            ],
        ],
        'tracked-assets.manage' => [
            'module' => 'Echipamente',
            'label' => 'Administrează echipamentele',
            'description' => 'Creează și modifică fișele echipamentelor individuale.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global'],
        ],
        'projects.view' => [
            'module' => 'Proiecte',
            'label' => 'Consultă proiectele',
            'description' => 'Vede proiectele și planurile de materiale disponibile.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'projects.manage' => [
            'module' => 'Proiecte',
            'label' => 'Administrează proiectele',
            'description' => 'Creează proiecte și modifică planurile și starea lor.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global', 'manager' => 'global'],
        ],
        'transfers.view' => [
            'module' => 'Transferuri',
            'label' => 'Consultă transferurile',
            'description' => 'Vede transferurile globale, locale sau alocate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'sofer' => 'assigned_records',
            ],
        ],
        'transfers.create' => [
            'module' => 'Transferuri',
            'label' => 'Creează transferuri',
            'description' => 'Inițiază un transfer în domeniul operațional permis.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'transfers.update' => [
            'module' => 'Transferuri',
            'label' => 'Modifică transferurile',
            'description' => 'Modifică un transfer încă editabil și relansează aprobările când este necesar.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de starea, arhivarea și locațiile transferului.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'transfers.approve' => [
            'module' => 'Transferuri',
            'label' => 'Aprobă transferurile',
            'description' => 'Înregistrează decizia pentru aprobările operaționale eligibile.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de locația aprobării, revizia și starea transferului.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'transfers.receive' => [
            'module' => 'Transferuri',
            'label' => 'Confirmă primirea transferurilor',
            'description' => 'Confirmă sosirea și actualizează locația bunurilor și stocurile.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'condition' => 'Este permis numai în starea potrivită și la destinația autorizată.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'destination_location', 'sef-santier' => 'destination_location',
            ],
        ],
        'transfers.cancel' => [
            'module' => 'Transferuri',
            'label' => 'Anulează transferurile',
            'description' => 'Închide controlat un transfer care nu mai trebuie continuat.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de starea și arhivarea transferului.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'transfers.archive' => [
            'module' => 'Transferuri',
            'label' => 'Arhivează transferurile',
            'description' => 'Arhivează transferurile deja închise fără a șterge istoricul.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'condition' => 'Este permis numai pentru transferuri finalizate sau anulate.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'tasks.view' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Consultă sarcinile',
            'description' => 'Vede sarcinile globale, locale sau alocate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'sofer' => 'assigned_records',
            ],
        ],
        'tasks.create' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Creează sarcini',
            'description' => 'Creează sarcini independente pentru șoferi.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'tasks.update' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Modifică sarcinile',
            'description' => 'Modifică sarcinile independente care nu sunt blocate.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de legătura cu un transfer și de starea sarcinii.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'tasks.assign' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Alocă șoferi',
            'description' => 'Alege șoferul și gestionează realocarea unei sarcini.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'condition' => 'Sarcina trebuie să fie activă, iar șoferul eligibil.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'tasks.respond' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Răspunde la sarcinile alocate',
            'description' => 'Acceptă, refuză, estimează, pornește sau solicită realocarea sarcinii proprii.',
            'risk' => 'elevated',
            'direct_scope' => 'assigned_records',
            'condition' => 'Utilizatorul trebuie să lucreze în spațiul de șofer și să fie alocat sarcinii.',
            'grants' => ['sofer' => 'assigned_records'],
        ],
        'tasks.comment' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Adaugă comentarii la sarcini',
            'description' => 'Adaugă observații la sarcinile pe care le poate consulta.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'condition' => 'Sarcina nu trebuie să fie blocată operațional.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'sofer' => 'assigned_records',
            ],
        ],
        'tasks.transition' => [
            'module' => 'Sarcini șoferi',
            'label' => 'Schimbă starea sarcinilor',
            'description' => 'Aplică tranzițiile operaționale disponibile unei sarcini.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de starea curentă și de regulile fluxului.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'reception-intakes.view' => [
            'module' => 'Recepții',
            'label' => 'Consultă documentele de procesat',
            'description' => 'Vede documentele preliminare globale, locale sau trimise personal.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'muncitor' => 'personal',
            ],
        ],
        'reception-intakes.create' => [
            'module' => 'Recepții',
            'label' => 'Trimite documente spre procesare',
            'description' => 'Încarcă documente preliminare pentru o locație activă.',
            'risk' => 'elevated',
            'direct_scope' => 'selected_location',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'muncitor' => 'selected_location',
            ],
        ],
        'reception-intakes.cancel' => [
            'module' => 'Recepții',
            'label' => 'Închide documente fără recepție',
            'description' => 'Închide justificat documentele care nu vor fi transformate în recepție.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'condition' => 'Documentele trebuie să fie încă în starea de procesare.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'receptions.view' => [
            'module' => 'Recepții',
            'label' => 'Consultă recepțiile',
            'description' => 'Vede recepțiile globale sau din locațiile administrate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'contabil' => 'global',
            ],
        ],
        'receptions.create' => [
            'module' => 'Recepții',
            'label' => 'Înregistrează recepții',
            'description' => 'Transformă documentele sau înregistrează direct o recepție în stoc.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'reception-documents.upload' => [
            'module' => 'Recepții',
            'label' => 'Încarcă documente de recepție',
            'description' => 'Atașează imagini sau PDF-uri la fluxul de recepție.',
            'risk' => 'elevated',
            'direct_scope' => 'selected_location',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'muncitor' => 'selected_location',
            ],
        ],
        'reception-details.edit-all' => [
            'module' => 'Recepții',
            'label' => 'Corectează toate detaliile recepției',
            'description' => 'Modifică metadatele comerciale și documentele unei recepții existente.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'reception-details.edit-expiration' => [
            'module' => 'Recepții',
            'label' => 'Corectează expirarea loturilor',
            'description' => 'Modifică data de expirare în recepțiile locațiilor administrate.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'grants' => ['super-admin' => 'global', 'admin' => 'global', 'gestionar-baza' => 'assigned_locations'],
        ],
        'accounting.edit-operations' => [
            'module' => 'Recepții',
            'label' => 'Excepție contabilă pentru corectarea operațiunilor',
            'description' => 'Permite corectarea controlată a detaliilor pentru înregistrările deja vizibile.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'grants' => [],
        ],
        'negotiated-orders.view' => [
            'module' => 'Comenzi negociate',
            'label' => 'Consultă comenzile negociate',
            'description' => 'Vede comenzile negociate și legătura lor cu recepțiile.',
            'risk' => 'elevated',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'negotiated-orders.manage' => [
            'module' => 'Comenzi negociate',
            'label' => 'Administrează comenzile negociate',
            'description' => 'Creează, modifică și anulează comenzile negociate.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'consumption-reports.view' => [
            'module' => 'Consum',
            'label' => 'Consultă consumurile',
            'description' => 'Vede consumurile globale sau din locațiile administrate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'contabil' => 'global',
            ],
        ],
        'consumption-reports.create' => [
            'module' => 'Consum',
            'label' => 'Înregistrează consumuri',
            'description' => 'Scade controlat materiale din stocul unei locații autorizate.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
            ],
        ],
        'consumption-reports.correct' => [
            'module' => 'Consum',
            'label' => 'Corectează consumuri',
            'description' => 'Înlocuiește controlat un consum și păstrează reviziile și motivul.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'condition' => 'Corecția este auditată și nu șterge istoricul anterior.',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'custody.view' => [
            'module' => 'Custodie',
            'label' => 'Consultă custodia',
            'description' => 'Vede custodia globală, locală sau personală.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
                'sofer' => 'personal', 'muncitor' => 'personal',
            ],
        ],
        'custody.initiate' => [
            'module' => 'Custodie',
            'label' => 'Inițiază operațiuni de custodie',
            'description' => 'Inițiază predarea, alocarea sau returul bunurilor eligibile.',
            'risk' => 'elevated',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de bunul curent, persoanele implicate și locația operațiunii.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
                'sofer' => 'personal', 'muncitor' => 'personal',
            ],
        ],
        'custody.manage' => [
            'module' => 'Custodie',
            'label' => 'Confirmă operațiuni de custodie',
            'description' => 'Confirmă operațiunile pentru care utilizatorul este persoană sau responsabil eligibil.',
            'risk' => 'sensitive',
            'direct_scope' => 'visible_records',
            'condition' => 'Depinde de rolul în operațiune și de aprobările deja înregistrate.',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations',
                'sofer' => 'personal', 'muncitor' => 'personal',
            ],
        ],
        'reports.view' => [
            'module' => 'Rapoarte',
            'label' => 'Consultă rapoartele',
            'description' => 'Vede rapoartele globale sau limitate la locațiile administrate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'contabil' => 'global',
            ],
        ],
        'alerts.view' => [
            'module' => 'Alerte',
            'label' => 'Consultă alertele',
            'description' => 'Vede alertele globale sau asociate locațiilor administrate.',
            'risk' => 'normal',
            'direct_scope' => 'visible_records',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global', 'manager' => 'global',
                'gestionar-baza' => 'assigned_locations', 'sef-santier' => 'assigned_locations', 'contabil' => 'global',
            ],
        ],
        'alerts.manage' => [
            'module' => 'Alerte',
            'label' => 'Administrează regulile de alertare',
            'description' => 'Creează și elimină excepțiile de alertare permise.',
            'risk' => 'sensitive',
            'direct_scope' => 'global',
            'grants' => ['super-admin' => 'global', 'admin' => 'global'],
        ],
        'qr.scan' => [
            'module' => 'Teren',
            'label' => 'Scanează coduri QR',
            'description' => 'Caută un echipament prin cod QR și deschide fișa permisă.',
            'risk' => 'normal',
            'direct_scope' => 'lookup',
            'grants' => [
                'super-admin' => 'global', 'admin' => 'global', 'dispecer' => 'global',
                'gestionar-baza' => 'lookup', 'sef-santier' => 'lookup', 'sofer' => 'lookup', 'muncitor' => 'lookup',
            ],
        ],
        'access-database-tools' => [
            'module' => 'Sistem',
            'label' => 'Folosește instrumentele bazei de date',
            'description' => 'Acces rezervat contului protejat pentru operațiuni tehnice de sistem.',
            'risk' => 'protected',
            'driver' => 'gate',
            'direct_scope' => 'protected_identity',
            'grants' => ['super-admin' => 'protected_identity'],
        ],
    ],
];
