@extends('layouts.app')

@section('title', 'Excepții: '.$user->name)

@section('content')
<div class="resource-shell">
    <div class="mb-4"><a href="{{ route('access.show', $user) }}" class="text-decoration-none small"><i class="fa-solid fa-arrow-left me-1"></i>Accesul utilizatorului</a><h1 class="h3 mt-2 mb-1">Excepții individuale: {{ $user->name }}</h1><p class="text-muted mb-0">Acordă punctual drepturi suplimentare fără modificarea rolurilor utilizatorului.</p></div>

    <div class="alert alert-warning"><i class="fa-solid fa-triangle-exclamation me-2"></i>Excepțiile se aplică numai acestui utilizator. Pentru o nevoie comună mai multor persoane, modifică rolul potrivit.</div>
    @if($removalOnlyPermissions)<div class="alert alert-info"><strong>Drepturi existente disponibile numai pentru retragere:</strong> nu pot fi acordate din nou după debifare.</div>@endif

    @if($contexts->isNotEmpty())
        <div class="card mb-4"><div class="card-header bg-white"><strong>Justificări existente</strong></div><div class="list-group list-group-flush">@foreach($contexts as $context)<div class="list-group-item"><strong>{{ config('access.permissions.'.$context->permission->name.'.label', $context->permission->name) }}</strong><code class="ms-1">{{ $context->permission->name }}</code><div class="small">{{ $context->reason }}</div></div>@endforeach</div></div>
    @endif

    <form method="post" action="{{ route('access.exceptions.preview', $user) }}" class="resource-form-card">
        @csrf
        <div class="resource-form-section"><div class="resource-form-section-title">Drepturi disponibile pentru excepții</div>@if($removalOnlyPermissions)<div class="card border-warning mb-3"><div class="card-header bg-warning-subtle"><strong>Excepții vechi sau rezervate</strong></div><div class="list-group list-group-flush">@foreach($removalOnlyPermissions as $ability)<label class="list-group-item d-flex gap-3 align-items-start"><input class="form-check-input mt-1" type="checkbox" name="permissions[]" value="{{ $ability }}" @checked(in_array($ability, old('permissions', $selectedPermissions), true))><span><strong>{{ config('access.permissions.'.$ability.'.label', $ability) }}</strong><code class="ms-1">{{ $ability }}</code><span class="d-block small text-muted">Poate fi păstrată sau retrasă, dar nu poate fi acordată din nou aici.</span></span></label>@endforeach</div></div>@endif<div class="accordion" id="exception-permissions">@foreach($permissionsByModule as $module => $permissions)<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button {{ $loop->first ? '' : 'collapsed' }}" type="button" data-bs-toggle="collapse" data-bs-target="#exception-module-{{ $loop->index }}">{{ $module }} <span class="badge text-bg-light border ms-2">{{ $permissions->count() }}</span></button></h2><div id="exception-module-{{ $loop->index }}" class="accordion-collapse collapse {{ $loop->first ? 'show' : '' }}" data-bs-parent="#exception-permissions"><div class="list-group list-group-flush">@foreach($permissions as $entry)<label class="list-group-item d-flex gap-3 align-items-start"><input class="form-check-input mt-1" type="checkbox" name="permissions[]" value="{{ $entry['ability'] }}" @checked(in_array($entry['ability'], old('permissions', $selectedPermissions), true))><span><strong>{{ $entry['definition']['label'] }}</strong><code class="ms-1">{{ $entry['ability'] }}</code><span class="d-block small text-muted">{{ $entry['definition']['description'] }}</span></span></label>@endforeach</div></div></div>@endforeach</div></div>
        <div class="resource-form-section"><div class="resource-form-section-title">Justificarea schimbării</div><label class="form-label">De ce este necesară această configurație?</label><textarea name="reason" class="form-control" rows="3" minlength="10" maxlength="1000" placeholder="Descrie situația concretă și motivul excepției.">{{ old('reason', $preview['reason'] ?? '') }}</textarea><div class="form-text">Obligatorie când se adaugă sau se retrage cel puțin un drept.</div></div>
        <div class="resource-form-actions-bar"><a href="{{ route('access.show', $user) }}" class="btn btn-outline-secondary">Renunță</a><button class="btn btn-primary"><i class="fa-solid fa-magnifying-glass me-1"></i>Previzualizează modificările</button></div>
    </form>

    @if($preview)
        <div class="card border-primary mt-4"><div class="card-header bg-primary text-white"><strong>Previzualizarea excepțiilor</strong></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><h2 class="h6 text-success">Excepții adăugate</h2>@forelse($preview['added'] as $ability)<div><i class="fa-solid fa-plus me-1"></i>{{ config('access.permissions.'.$ability.'.label', $ability) }} <code>{{ $ability }}</code></div>@empty<span class="text-muted">Niciuna</span>@endforelse</div><div class="col-md-6"><h2 class="h6 text-danger">Excepții retrase</h2>@forelse($preview['removed'] as $ability)<div><i class="fa-solid fa-minus me-1"></i>{{ config('access.permissions.'.$ability.'.label', $ability) }} <code>{{ $ability }}</code></div>@empty<span class="text-muted">Niciuna</span>@endforelse</div></div>@if($preview['reason'])<div class="mt-3"><strong>Motiv:</strong> {{ $preview['reason'] }}</div>@endif</div>@if($preview['added'] || $preview['removed'])<div class="card-footer d-flex justify-content-end"><form method="post" action="{{ route('access.exceptions.update', $user) }}">@csrf @method('put')<input type="hidden" name="confirmation_token" value="{{ $preview['token'] }}"><button class="btn btn-success"><i class="fa-solid fa-check me-1"></i>Aplică excepțiile verificate</button></form></div>@else<div class="card-footer text-muted">Nu există modificări de aplicat.</div>@endif</div>
    @endif
</div>
@endsection
